### ISSUE TITLE
Logout not functioning

### ISSUE THREAD

**Issue by Fishwithshoes** [mrbrian/CPSC441_Project#25]
When logging into the game, it is not possible to logout. Typing /logout before joining a room will generate no response and further input will generate a broken pipe. /logout inside of the game will generate a broken pipe when further commands such as /setalias and /leave are executed.

**Comment by Fishwithshoes** [comment]
Sorry, not a issue, just not implemented.

**Comment by mrbrian** [comment]
updated, the reading keyboard thread wasnt closing and now server tells client to disconnect
